# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a3b18ca639965cd573cc9fa438e907e9f4fdd9cba13ff61c0b5eca814c5f9f36b94a846ee34b109017cc2465da2a61652c321dcb96ae8a682813f81eb2d5e039

test:
  secret_key_base: d412f7c4ac2d406cbf010352cee8d2d4c40224e8f300b9366593d7126631f0f9846a1f32e009aa44b37a03ffab05713dc399318d9e87c383a804d804a38eef87

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
